package main

import (
	"database/sql"
	"fmt"
	"log"
	"time"

	"github.com/jmoiron/sqlx"
)

func createTable(db *sql.DB, table string) {
	sql := `
	create table  if not exists` + table + `(
	id bigint primary key generated by default as identity,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	phone varchar(15) not null,
	email varchar(50) not null,
	birth date not null
	);
	`
}
func createInfoToDB(listInfo *) {
	sql := "insert into contact_list(first_name,last_name,phone,email.birth) values (:first_name,:last_name,:phone,:email,:birth) "
	 
	res,err:=db.Exec(sql,listInfo)

	if err!=nil{
		return
	}
}

func main() {

	db, err := sqlx.Connect("postgres", "postgres://postgres:@127.0.0.1/contact_list")
	if err != nil {
		log.Fatal(err)
	}
	var (
		firstName, lastName, email, number, birth string
	)
	fmt.Print("First name: ")
	fmt.Scanln(&firstName)

	fmt.Print("Last name: ")
	fmt.Scanln(&lastName)

	fmt.Print("Phone no: ")
	fmt.Scanln(&number)

	fmt.Print("Email: ")
	fmt.Scanln(&email)

	fmt.Print("Date of birth: ")
	fmt.Scanln(&birth)
	str := birth
	_, err := time.Parse(time.DateOnly, str)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("SAVED!")
}
